// Code generated by hashicorp/terraform-plugin-codegen-kubernetes; THIS FILE IS FOR YOU TO EDIT
//
// This file contains function signatures for implementing CRUD hooks. 
// You need to provide the implementation for these functions. 
//
// This code was written by a robot on {{ .GeneratedTimestamp.Format "Jan 02, 2006 15:04:05 UTC" }}.

package {{ .ResourceConfig.Package }}

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource"
)

{{ if .ResourceConfig.Generate.CRUDAutoOptions.Hooks.BeforeCreate -}}
func (r *{{ .ResourceConfig.Kind }}) BeforeCreate(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse, m *{{ .ResourceConfig.Kind }}Model) {
	// TODO: Add BeforeCreate logic
}
{{ end }}

{{ if .ResourceConfig.Generate.CRUDAutoOptions.Hooks.AfterCreate -}}
func (r *{{ .ResourceConfig.Kind }}) AfterCreate(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse, m *{{ .ResourceConfig.Kind }}Model) {
    // TODO: Add AfterCreate logic
}
{{ end }}

{{ if .ResourceConfig.Generate.CRUDAutoOptions.Hooks.BeforeRead -}}
func (r *{{ .ResourceConfig.Kind }}) BeforeRead(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse, m *{{ .ResourceConfig.Kind }}Model) {
	// TODO: Add BeforeRead logic
}
{{ end }}

{{ if .ResourceConfig.Generate.CRUDAutoOptions.Hooks.AfterRead -}}
func (r *{{ .ResourceConfig.Kind }}) AfterRead(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse, m *{{ .ResourceConfig.Kind }}Model) {
    // TODO: Add AfterRead logic
}
{{ end }}

{{ if .ResourceConfig.Generate.CRUDAutoOptions.Hooks.BeforeUpdate -}}
func (r *{{ .ResourceConfig.Kind }}) BeforeUpdate(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse, m *{{ .ResourceConfig.Kind }}Model) {
	// TODO: Add BeforeUpdate logic
}
{{ end }}

{{ if .ResourceConfig.Generate.CRUDAutoOptions.Hooks.AfterUpdate -}}
func (r *{{ .ResourceConfig.Kind }}) AfterUpdate(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse, m *{{ .ResourceConfig.Kind }}Model) {
    // TODO: Add AfterUpdate logic
}
{{ end }}

{{ if .ResourceConfig.Generate.CRUDAutoOptions.Hooks.BeforeDelete -}}
func (r *{{ .ResourceConfig.Kind }}) BeforeDelete(ctx context.Context, req resource.DestroyRequest, resp *resource.DestroyResponse, m *{{ .ResourceConfig.Kind }}Model) {
	// TODO: Add BeforeDelete logic
}
{{ end }}

{{ if .ResourceConfig.Generate.CRUDAutoOptions.Hooks.AfterDelete -}}
func (r *{{ .ResourceConfig.Kind }}) AfterDelete(ctx context.Context, req resource.DestroyRequest, resp *resource.DestroyResponse, m *{{ .ResourceConfig.Kind }}Model) {
    // TODO: Add AfterDelete logic
}
{{ end }}