// Code generated by hashicorp/terraform-plugin-codegen-kubernetes; THIS FILE IS FOR YOU TO EDIT
//
// This file contains function signatures for implementing CRUD hooks. 
// You need to provide the implementation for these functions. 
//
// This code was written by a robot on {{ .GeneratedTimestamp.Format "Jan 02, 2006 15:04:05 UTC" }}.

package {{ .ResourceConfig.Package }}

{{ if .ResourceConfig.Generate.CRUDAutoOptions.Hooks.BeforeCreate -}}
func (r *{{ .ResourceConfig.Kind }}) BeforeCreate(m *{{ .ResourceConfig.Kind }}Model, ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	// TODO: Add BeforeCreate logic
}
{{ end }}

{{ if .ResourceConfig.Generate.CRUDAutoOptions.Hooks.AfterCreate -}}
func (r *{{ .ResourceConfig.Kind }}) AfterCreate(m *{{ .ResourceConfig.Kind }}Model, ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
    // TODO: Add AfterCreate logic
}
{{ end }}

{{ if .ResourceConfig.Generate.CRUDAutoOptions.Hooks.BeforeRead -}}
func (r *{{ .ResourceConfig.Kind }}) BeforeRead(m *{{ .ResourceConfig.Kind }}Model, ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	// TODO: Add BeforeRead logic
}
{{ end }}

{{ if .ResourceConfig.Generate.CRUDAutoOptions.Hooks.AfterRead -}}
func (r *{{ .ResourceConfig.Kind }}) AfterRead(m *{{ .ResourceConfig.Kind }}Model, ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
    // TODO: Add AfterRead logic
}
{{ end }}

{{ if .ResourceConfig.Generate.CRUDAutoOptions.Hooks.BeforeUpdate -}}
func (r *{{ .ResourceConfig.Kind }}) BeforeUpdate(m *{{ .ResourceConfig.Kind }}Model, ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	// TODO: Add BeforeUpdate logic
}
{{ end }}

{{ if .ResourceConfig.Generate.CRUDAutoOptions.Hooks.AfterUpdate -}}
func (r *{{ .ResourceConfig.Kind }}) AfterUpdate(m *{{ .ResourceConfig.Kind }}Model, ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
    // TODO: Add AfterUpdate logic
}
{{ end }}