// Code generated by tools/gen/schema_openapi_v3.go; DO NOT EDIT
//
// This file contains the list of constructors for resources that have been autogenerated.
//
// This code was written by a robot on Apr 21, 2023 18:20:45 UTC.

package provider

import "github.com/hashicorp/terraform-plugin-framework/resource"

var resources = []func() resource.Resource{
	NewConfigMap,
}
